# إعدادات تليجرام
TELEGRAM_TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN'
TELEGRAM_CHAT_ID = 'YOUR_TELEGRAM_CHAT_ID'

# إعدادات منصة التداول
EXCHANGE_NAME = 'binance'
SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'XRP/USDT', 'LTC/USDT', 'BCH/USDT', 'EOS/USDT', 'BNB/USDT', 'ADA/USDT', 'TRX/USDT', 'XLM/USDT', 'LINK/USDT', 'DOT/USDT', 'YFI/USDT', 'UNI/USDT', 'AAVE/USDT', 'SUSHI/USDT', 'MKR/USDT', 'COMP/USDT', 'SNX/USDT', 'CRV/USDT', 'SOL/USDT', 'AVAX/USDT', 'FTT/USDT', 'GRT/USDT', '1INCH/USDT', 'ALGO/USDT', 'ATOM/USDT', 'BTT/USDT', 'CHZ/USDT', 'DASH/USDT', 'DOGE/USDT', 'ENJ/USDT', 'ETC/USDT', 'FIL/USDT', 'HOT/USDT', 'KSM/USDT', 'MANA/USDT', 'NEO/USDT', 'OMG/USDT', 'ONT/USDT', 'RVN/USDT', 'SXP/USDT', 'THETA/USDT', 'VET/USDT', 'XEM/USDT', 'ZIL/USDT', 'ZRX/USDT', 'BAT/USDT', 'KNC/USDT']  # 50 عملة
TIMEFRAME = '15m'  # فريم 15 دقيقة
